# Generated by Django 4.2.7 on 2023-11-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Prefiro não informar')], max_length=2)),
                ('data_nacimento', models.DateField()),
                ('endereco', models.TextField()),
            ],
        ),
    ]
