# Generated by Django 4.2.7 on 2023-11-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('descricao', models.CharField(blank=True, max_length=150, null=True)),
                ('tamanho', models.CharField(blank=True, choices=[('P', 'Small'), ('M', 'Medio'), ('L', 'Large')], max_length=2, null=True)),
            ],
        ),
    ]
